import matplotlib.pyplot as plt
import numpy as np

# time domain in which we sample
x = np.linspace(0, 20, 50)

# random function to simulate sampled signal
y = np.sin(x + 1) + np.cos(x ** 2)

# here we can setup baseline position
bottom = -0.1

# set label for legend
label = "delta"

markerline, stemline, baseline = plt.stem(x, y, bottom=bottom, label=label, use_line_collection=True)

# we use setp() here to setup
# multiple properties of lines generated by stem()
plt.setp(markerline, color='red', marker='o')
plt.setp(stemline, color='blue', linestyle=':')
plt.setp(baseline, color='grey', linewidth=2, linestyle='-')

plt.legend()
plt.show()
